hero_diary/urls.py
from django.contrib import admin
from django.urls import path

from diary.views import CheckHero, CreateHero, StartView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("create_hero", CreateHero.as_view(), name="create-hero"),
    path("view_hero/<int:hero_id>", CheckHero.as_view(), name="hero"),
    path("", StartView.as_view(), name="index"),
]

diary/models.py
import math
from random import choice

from django.db import models

from diary import consts


class Hero(models.Model):
    name = models.CharField(max_length=255)
    experience = models.IntegerField(default=0)
    strength = models.IntegerField()
    agility = models.IntegerField()
    vitality = models.IntegerField()
    wisdom = models.IntegerField()
    charisma = models.IntegerField()
    gold = models.IntegerField()
    last_action = models.DateTimeField(auto_created=True)
    LOCATION = (
        (consts.LOCATION_TOWN, "Town"),
        (consts.LOCATION_ROAD_KILLING_FIELDS, "In road to Killing fields"),
        (consts.LOCATION_KILLING_FIELDS, "Killing fields"),
        (consts.LOCATION_ROAD_TOWN, "In road to Town"),
    )
    location = models.IntegerField(choices=LOCATION, default=1)

    @property
    def capacity(self):
        return self.strength + consts.BASE_CAPACITY

    @property
    def speed_of_travel(self):
        return consts.BASE_SPEED_OF_TRAVEL + self.agility * consts.SPEED_OF_TRAVEL_MULTIPLIER

    @property
    def luck(self):
        return self.wisdom * consts.LUCK_MULTIPLIER

    @property
    def merchant_discount(self):
        return math.log2(self.charisma)

    @property
    def level(self):
        current_exp = max(self.experience, 1)
        logaritmic_level = math.log(current_exp, 8)
        return math.ceil(logaritmic_level)

    def add_random_attribute(self):
        option = choice(["strength", "agility", "vitality", "wisdom", "charisma"])
        if option == "strength":
            self.strength += +1
        if option == "agility":
            self.agility += +1
        if option == "vitality":
            self.vitality += +1
        if option == "wisdom":
            self.wisdom += +1
        if option == "charisma":
            self.charisma += +1
        return option


class Item(models.Model):
    QUALITY = (
        (1, "normal"),
        (4, "rare"),
        (16, "unique"),
        (64, "legendary"),
    )

    name = models.CharField(max_length=255)
    quality = models.IntegerField(choices=QUALITY)
    owner = models.ForeignKey(Hero, on_delete=models.CASCADE, related_name="items")

    @property
    def price(self):
        return self.owner.level * self.quality

    def __str__(self):
        return f"<{self.get_quality_display()}> {self.name}"


class Equipment(models.Model):
    PREFIXES = (
        (1, "Awful"),
        (4, "Poor"),
        (16, "Normal"),
        (64, "Good"),
        (256, "Excellent"),
        (1024, "Legendary"),
    )
    prefix = models.IntegerField(choices=PREFIXES)
    SUFFIX = (
        (1, "of Child"),
        (4, "of Mouse"),
        (16, "of Minotaur"),
        (64, "of Dragon"),
        (256, "of God"),
        (1024, "of Hamster"),
    )
    suffix = models.IntegerField(choices=SUFFIX, default=1)
    modifier = models.IntegerField()
    owner = models.ForeignKey(Hero, on_delete=models.CASCADE, related_name="equipments")
    SLOTS = (
        (1, "Helmet"),
        (2, "Shoulders"),
        (3, "Armor"),
        (4, "Gloves"),
        (5, "Legs"),
        (6, "Shoes"),
        (7, "Sword"),
        (8, "Shield"),
        (9, "Cape"),
    )
    slot = models.IntegerField(choices=SLOTS)

    @property
    def price(self):
        return self.prefix * self.suffix * self.slot

    @property
    def price_next(self):
        return self.prefix * self.suffix * self.slot * 4

    def __str__(self):
        return f"{self.get_prefix_display()} {self.get_slot_display()} {self.get_suffix_display()} {self.modifier}"

diary/views.py
from datetime import datetime, timedelta, timezone
from random import choice, randint
from types import FunctionType
from typing import Dict

from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from faker import Faker

from diary import consts, models

fake = Faker(["pl_PL", "sv_SE", "hi_IN"])

from rq import Queue
from worker import conn



class StartView(View):
    def get(self, request):
        heroes = models.Hero.objects.all()
        from utils import count_words_at_url
        q = Queue(connection=conn)
        result = q.enqueue(count_words_at_url, 'http://heroku.com')
        return render(request, "index.html", context={"heroes": heroes})


class CreateHero(View):
    def get(self, request):
        models.Hero.objects.create(
            name=fake.name(),
            strength=randint(3, 18),
            agility=randint(3, 18),
            vitality=randint(3, 18),
            wisdom=randint(3, 18),
            charisma=randint(3, 18),
            gold=0,
            last_action=datetime.now(),
        )
        return redirect("index")


class Action:
    def __init__(self, action_type: consts.ActionType):
        self.action_type = action_type

    @property
    def time(self):
        return consts.ACTION_SPEED.get(self.action_type, 0)


class Diary:
    MAX_ACTION_COUNT = 100

    def __init__(self, hero: models.Hero):
        self._hero = hero
        self.messages = []

    def process_story(self):
        counter = 0
        while self.can_do_next_action() and counter < self.MAX_ACTION_COUNT:
            action = self.predict_action()
            self.make_action(action)
            counter += 1
        self._hero.save()  # Save hero only one

    def can_do_next_action(self):
        action = self.predict_action()
        timedelta_from_last_action = datetime.now(timezone.utc) - self._hero.last_action
        return timedelta(seconds=action.time) < timedelta_from_last_action

    def predict_action(self) -> Action:
        if self._hero.location == consts.LOCATION_TOWN:
            return self.predict_action_in_town()
        if self._hero.location == consts.LOCATION_ROAD_KILLING_FIELDS:
            return Action(consts.ActionType.KILLING_FIELD)
        if self._hero.location == consts.LOCATION_KILLING_FIELDS:
            return self.predict_action_in_killing_fields()
        return Action(consts.ActionType.TOWN)

    def predict_action_in_killing_fields(self) -> Action:
        if self._hero.items.count() < self._hero.capacity:
            return Action(consts.ActionType.KILL_MONSTER)
        return Action(consts.ActionType.TRAVEL_TO_TOWN)

    def predict_action_in_town(self) -> Action:
        if self._hero.items.count() > 0:
            return Action(consts.ActionType.SELL_ITEM)
        if self.can_buy_equipment():
            return Action(consts.ActionType.BUY_EQUIPMENT)
        return Action(consts.ActionType.TRAVEL_TO_KILLING_FIELD)

    def can_buy_equipment(self) -> bool:
        price_for_slot_upgrade = self.get_price_for_upgrade()
        for key, value in price_for_slot_upgrade.items():
            if value <= self._hero.gold:
                return True
        return False

    def get_price_for_upgrade(self):
        equipments = self._hero.equipments.all()
        price_for_slot_upgrade = {k: 1 for k, _ in models.Equipment.SLOTS}
        for equipment in equipments:
            price_for_slot_upgrade[equipment.slot] = equipment.price_next
        return price_for_slot_upgrade

    def make_action(self, action: Action):
        actions: Dict[consts.ActionType, FunctionType] = {
            consts.ActionType.SELL_ITEM: self.sell_item,
            consts.ActionType.BUY_EQUIPMENT: self.buy_equipments,
            consts.ActionType.TRAVEL_TO_KILLING_FIELD: self.travel_to_killing_field,
            consts.ActionType.KILLING_FIELD: self.killing_field,
            consts.ActionType.KILL_MONSTER: self.action_kill_monster,
            consts.ActionType.TRAVEL_TO_TOWN: self.action_travel_to_town,
            consts.ActionType.TOWN: self.action_in_town,
        }

        action_method = actions.get(action.action_type)
        if action_method:
            action_method(action)

    def buy_equipments(self, action: Action):
        for slot, value in self.get_price_for_upgrade().items():
            if value <= self._hero.gold:
                equipment = self.buy_equipment(slot, value)
                self._hero.last_action += timedelta(seconds=action.time)
                self.messages.append(f"{self._hero.last_action} - buy equipment {equipment}")

    def action_in_town(self, action: Action):
        self._hero.location = consts.LOCATION_TOWN
        self._hero.last_action += timedelta(seconds=action.time)
        self.messages.append(f"{self._hero.last_action} - in  Town")

    def action_travel_to_town(self, action: Action):
        self._hero.location = consts.LOCATION_ROAD_TOWN
        self._hero.last_action += timedelta(seconds=action.time)
        self.messages.append(f"{self._hero.last_action} - travel to  Town")

    def action_kill_monster(self, action: Action):
        self._hero.experience += +randint(3, 5)
        self._hero.last_action += timedelta(seconds=action.time)
        monster = choice(consts.LIST_OF_MONSTER)
        self.messages.append(f"{self._hero.last_action} - kill {monster}")
        if randint(1, 100) > 99:
            attribute = self._hero.add_random_attribute()
            self.messages.append(f"{self._hero.last_action} - get attribute {attribute}")
        item = self.generate_item()
        self.messages.append(f"{self._hero.last_action} - get {item}")

    def killing_field(self, action: Action):
        self._hero.location = consts.LOCATION_KILLING_FIELDS
        self._hero.last_action += timedelta(seconds=action.time)
        self.messages.append(f"{self._hero.last_action} - in  KILLING_FIEL")

    def travel_to_killing_field(self, action: Action):
        self._hero.location = consts.LOCATION_ROAD_KILLING_FIELDS
        self._hero.last_action += timedelta(seconds=action.time)
        self.messages.append(f"{self._hero.last_action} - travel to  KILLING_FIEL")

    def sell_item(self, action: Action):
        item = self._hero.items.first()
        self._hero.gold += item.price
        self._hero.last_action += timedelta(seconds=action.time)
        self.messages.append(
            f"{self._hero.last_action} - sell item {item} - price: {item.price} - gold {self._hero.gold}"
        )
        item.delete()

    def buy_equipment(self, slot: int, value: int) -> models.Item:
        self._hero.gold -= value
        equipment = self._hero.equipments.filter(slot=slot).first()
        if equipment:
            if equipment.prefix > equipment.suffix:
                equipment.suffix *= 4
            else:
                equipment.prefix *= 4
            equipment.save()
        else:
            equipment = models.Equipment.objects.create(prefix=1, suffix=1, slot=slot, owner=self._hero, modifier=0)
        return equipment

    def generate_item(self) -> models.Item:
        roll = randint(1, 64)
        if roll == 64:
            quality = 64
        elif roll >= 64 - 4:
            quality = 16
        elif roll >= 64 - 16:
            quality = 4
        else:
            quality = 1
        name = choice(consts.LIST_OF_ITEMS)
        return models.Item.objects.create(quality=quality, name=name, owner=self._hero)


class CheckHero(View):
    def get(self, request, hero_id):
        hero = get_object_or_404(models.Hero, pk=hero_id)
        diary = Diary(hero)
        diary.process_story()
        return render(request, "hero_page.html", context={"hero": hero, "diary": diary})

diary/templates/hero_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="card col-12">
            <h5 class="card-header">{{hero.name}}</h5>
            <div class="card-body">
                <h5 class="card-title">last seen: {{ hero.last_action }}</h5>
                <p class="card-text">
                    Str: {{ hero.strength }}
                    Agi: {{ hero.agility }}
                    Vit: {{ hero.vitality }}
                    Wis: {{ hero.wisdom }}
                    Cha: {{ hero.charisma }}
                    Location: {{ hero.get_location_display }}
                    Exp: {{ hero.experience }}
                    Level: {{ hero.level }}
                    Gold: {{ hero.gold }}
                    Stash: {{ hero.items.count }} / {{ hero.capacity }}
                </p><p>
                    Equipment:</p>

                    {% for equipment in hero.equipments.all %}
                      <p>{{ equipment }}</p>
                    {% endfor%}

                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>

        {% for message in diary.messages %}
        <div class="card col-12">
            <h5 class="card-header">{{hero.name}}</h5>
            <div class="card-body">
                <p class="card-text">
                    {{ message }}
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</body>
</html>

diary/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="row">
        {% for hero in heroes %}
        <div class="card col-4">
            <h5 class="card-header">{{hero.name}}</h5>
            <div class="card-body">
                <h5 class="card-title">last seen: {{ hero.last_action }}</h5>
                <p class="card-text">
                    Str: {{ hero.strength }}
                    Agi: {{ hero.agility }}
                    Vit: {{ hero.vitality }}
                    Wis: {{ hero.wisdom }}
                    Cha: {{ hero.charisma }}
                </p>
                <a href="{% url 'hero' hero.id %}" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>

        {% endfor %}
        <div class="card col-4">
            <h5 class="card-header">Create New Hero</h5>
            <div class="card-body">
                <h5 class="card-title">Super</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="{% url 'create-hero' %}" class="btn btn-primary">Create</a>
            </div>
        </div>
    </div>
</div>
</body>
</html>